sudo: required

language: node_js

node_js: lts/*

env:
  - TZ='Europe/Paris'

services:
  - docker

before_install:
  - docker-compose --version
  - docker-compose up -d
  - docker ps

script:
  - yarn lint
  - yarn test --forceExit
